import config from 'nuxt-simple-robots/config'
import { defineEventHandler, setHeader } from 'h3'

const asArray = (v: any) => (Array.isArray(v) ? v : [v])
export default defineEventHandler(async (event) => {
  setHeader(event, 'Content-Type', 'text/plain')
  const debug = process.dev ? (`# Dev Mode: Generated by nuxt-simple-robots. Indexing is ${config.indexable ? 'enabled' : 'disabled'}\n`) : ''
  const sitemapLink = (config.sitemap && config.indexable ? asArray(config.sitemap) : []).map(path => `Sitemap: ${path}`).join('\n')
  const disallowedPaths = (config.indexable ? asArray(config.disallow) : ['/']).map(path => `Disallow: ${path}`).join('\n')
  return `${debug}User-agent: *\n${disallowedPaths}\n${sitemapLink}`
})
