import { defineEventHandler, setHeader } from 'h3'
import { disallow, indexable, sitemap } from '#nuxt-simple-robots/config'

const asArray = (v: any) => (Array.isArray(v) ? v : [v])
export default defineEventHandler(async (event) => {
  setHeader(event, 'Content-Type', 'text/plain')
  const debug = process.dev ? (`# Dev Mode: Generated by nuxt-simple-robots. Indexing is ${indexable ? 'enabled' : 'disabled'}\n`) : ''
  const sitemapLink = (sitemap && indexable ? asArray(sitemap || []) : []).map(path => `Sitemap: ${path}`).join('\n')
  const disallowedPaths = (indexable ? asArray(disallow || []) : ['/']).map(path => `Disallow: ${path}`).join('\n')
  return `${debug}User-agent: *\n${disallowedPaths}\n${sitemapLink}`
})
