import config from 'nuxt-simple-robots/config'
import { defineEventHandler, setHeader } from 'h3'

export default defineEventHandler(async (event) => {
  setHeader(event, 'Content-Type', 'text/plain')
  const debug = process.dev ? (`# Dev Mode: Generated by nuxt-simple-robots. Indexing is ${config.indexable ? 'enabled' : 'disabled'}\n`) : ''
  const sitemapLink = config.sitemap && config.indexable ? `\n\nSitemap: ${config.sitemap}` : ''
  const disallowedPaths = config.indexable ? [config.disallow] : ['/']
  return `${debug}User-agent: *\n${disallowedPaths.map(path => `Disallow: ${path}`)}${sitemapLink}`
})
