catalogMode: prefer
cleanupUnusedCatalogs: true
minimumReleaseAgeExclude:
  - eslint-plugin-harlanzw
  - nuxtseo-layer-devtools
  - nuxtseo-shared
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
  - undici-types
  - jose
  - tinyexec@1.2.2
packages:
  - devtools
  - playground
  - '!examples/**'
overrides:
  vite: ^8.0.16
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@fingerprintjs/botd': ^2.0.0
  '@iconify-json/tabler': ^1.2.35
  '@nuxt/devtools-kit': 4.0.0-alpha.7
  '@nuxt/devtools-ui-kit': 4.0.0-alpha.7
  '@nuxt/kit': ^4.4.8
  '@nuxtjs/i18n': ^10.4.0
  '@unocss/nuxt': ^66.7.0
  '@unocss/preset-icons': ^66.7.0
  '@unocss/preset-uno': ^66.7.0
  '@unocss/runtime': ^66.7.0
  '@vueuse/core': ^14.3.0
  better-sqlite3: ^12.10.0
  bumpp: ^11.1.0
  consola: ^3.4.2
  defu: ^6.1.7
  eslint: ^10.4.1
  eslint-plugin-harlanzw: ^0.17.0
  firebase-functions: ^7.2.5
  h3: ^1.15.11
  happy-dom: ^20.10.2
  nuxt: ^4.4.8
  nuxt-site-config: ^4.0.8
  nuxtseo-layer-devtools: ^5.2.3
  nuxtseo-shared: ^5.2.3
  pathe: ^2.0.3
  pkg-types: ^2.3.1
  radix3: ^1.1.2
  sirv: ^3.0.2
  std-env: ^4.1.0
  typescript: ^6.0.3
  ufo: ^1.6.4
  unbuild: ^3.6.1
  unocss: ^66.7.0
  vitest: ^4.1.8
  vue: ^3.5.35
  vue-router: ^5.1.0
catalogs:
  dev:
    '@arethetypeswrong/cli': ^0.18.3
    '@headlessui/vue': ^1.7.23
    '@iconify-json/carbon': ^1.2.23
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/ri': ^1.2.10
    '@nuxt/content': ^3.14.0
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/test-utils': ^4.0.3
    '@nuxtjs/color-mode': ^4.0.1
    '@vueuse/nuxt': ^14.3.0
    execa: ^9.6.1
    playwright-core: ^1.60.0
onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver
  - vue-demi
trustPolicyIgnoreAfter: 262800
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  protobufjs: true
  vue-demi: true
