catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - client

catalog:
  '@fingerprintjs/botd': ^2.0.0
  '@nuxt/kit': ^4.2.2
  consola: ^3.4.2
  defu: ^6.1.4
  nuxt-site-config: ^3.2.17
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  sirv: ^3.0.2
  std-env: ^3.10.0
  ufo: ^1.6.2

catalogs:
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@arethetypeswrong/cli': ^0.18.2
    '@headlessui/vue': ^1.7.23
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/ri': ^1.2.7
    '@iconify-json/tabler': ^1.2.26
    '@nuxt/content': ^3.10.0
    '@nuxt/devtools-kit': ^3.1.1
    '@nuxt/devtools-ui-kit': ^3.1.1
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/test-utils': ^3.23.0
    '@nuxtjs/color-mode': ^4.0.0
    '@nuxtjs/eslint-config-typescript': ^12.1.0
    '@nuxtjs/i18n': ^10.2.1
    '@unocss/nuxt': ^66.5.12
    '@unocss/preset-icons': ^66.5.12
    '@unocss/preset-uno': ^66.5.12
    '@unocss/runtime': ^66.5.12
    '@vueuse/nuxt': ^14.1.0
    better-sqlite3: ^12.5.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    execa: ^9.6.1
    firebase-functions: ^7.0.3
    floating-vue: ^5.2.2
    happy-dom: ^20.1.0
    nuxt: ^4.2.2
    playwright-core: ^1.57.0
    shiki: ^3.21.0
    typescript: ^5.9.3
    unocss: ^66.5.12
    vitest: ^4.0.16
    vue: ^3.5.26
    vue-router: ^4.6.4

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver
  - vue-demi
