catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
  - undici-types
  - jose

packages:
  - devtools
  - playground
  - '!examples/**'
overrides:
  vite: ^8.0.3
catalog:
  '@antfu/eslint-config': ^8.1.1
  '@fingerprintjs/botd': ^2.0.0
  '@iconify-json/tabler': ^1.2.32
  '@nuxt/devtools-kit': 4.0.0-alpha.3
  '@nuxt/devtools-ui-kit': ^3.2.4
  '@nuxt/kit': ^4.4.2
  '@nuxtjs/i18n': ^10.2.4
  '@unocss/nuxt': ^66.6.7
  '@unocss/preset-icons': ^66.6.7
  '@unocss/preset-uno': ^66.6.7
  '@unocss/runtime': ^66.6.7
  better-sqlite3: ^12.8.0
  bumpp: ^11.0.1
  consola: ^3.4.2
  defu: ^6.1.4
  eslint: ^10.1.0
  eslint-plugin-harlanzw: ^0.12.0
  firebase-functions: ^7.2.2
  h3: ^1.15.10
  happy-dom: ^20.8.8
  nuxt: ^4.4.2
  nuxt-site-config: ^4.0.6
  nuxtseo-layer-devtools: ^0.5.1
  nuxtseo-shared: ^0.9.0
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  shiki: ^4.0.2
  sirv: ^3.0.2
  std-env: ^4.0.0
  typescript: ^6.0.2
  ufo: ^1.6.3
  unocss: ^66.6.7
  vitest: ^4.1.1
  vue: ^3.5.31
  vue-router: ^5.0.4
catalogs:
  dev:
    '@arethetypeswrong/cli': ^0.18.2
    '@headlessui/vue': ^1.7.23
    '@iconify-json/carbon': ^1.2.20
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/ri': ^1.2.10
    '@nuxt/content': ^3.12.0
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/test-utils': ^4.0.0
    '@nuxtjs/color-mode': ^4.0.0
    '@vueuse/nuxt': ^14.2.1
    execa: ^9.6.1
    playwright-core: ^1.58.2
onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver
  - vue-demi
trustPolicyIgnoreAfter: 262800
