onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - protobufjs
  - unrs-resolver
  - vue-demi
packages:
  - client
catalog:
  '@antfu/eslint-config': ^6.4.1
  '@arethetypeswrong/cli': ^0.18.2
  '@fingerprintjs/botd': ^2.0.0
  '@headlessui/vue': ^1.7.23
  '@iconify-json/carbon': ^1.2.15
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/ri': ^1.2.6
  '@iconify-json/tabler': ^1.2.23
  '@nuxt/content': ^3.9.0
  '@nuxt/devtools-kit': ^3.1.1
  '@nuxt/devtools-ui-kit': ^3.1.1
  '@nuxt/kit': ^4.2.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/test-utils': ^3.21.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/eslint-config-typescript': ^12.1.0
  '@nuxtjs/i18n': ^10.2.1
  '@unocss/nuxt': ^66.5.10
  '@unocss/preset-icons': ^66.5.10
  '@unocss/preset-uno': ^66.5.10
  '@unocss/runtime': ^66.5.10
  '@vueuse/nuxt': ^14.1.0
  better-sqlite3: ^12.5.0
  bumpp: ^10.3.2
  consola: ^3.4.2
  defu: ^6.1.4
  eslint: ^9.39.1
  execa: ^9.6.1
  firebase-functions: ^7.0.1
  floating-vue: ^5.2.2
  happy-dom: ^20.0.11
  nuxt: ^4.2.1
  nuxt-site-config: ^3.2.11
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  playwright-core: ^1.57.0
  shiki: ^3.19.0
  sirv: ^3.0.2
  std-env: ^3.10.0
  typescript: ^5.9.3
  ufo: ^1.6.1
  unocss: ^66.5.10
  vitest: ^4.0.15
  vue: ^3.5.25
  vue-router: ^4.6.3
