interface BotPatternDefinition {
  name: string
  pattern: string
  secondaryPatterns?: string[]
}

interface BotCategoryDefinition {
  bots: BotPatternDefinition[]
  trusted: boolean
  type: string
}

interface PatternEntry {
  botIndex: number
  definitionIndex: number
  pattern: string
}

function collectPatterns(definitions: readonly BotCategoryDefinition[]): PatternEntry[] {
  const patterns = new Map<string, PatternEntry>()
  for (const [definitionIndex, definition] of definitions.entries()) {
    for (const [botIndex, bot] of definition.bots.entries()) {
      for (const sourcePattern of [bot.pattern, ...(bot.secondaryPatterns || [])]) {
        const pattern = sourcePattern.toLowerCase()
        patterns.set(pattern, {
          botIndex,
          definitionIndex,
          pattern,
        })
      }
    }
  }
  return [...patterns.values()]
}

function escapeRegExpPattern(value: string): string {
  return value
    .replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    .replaceAll('/', '\\/')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029')
}

function removeShadowedPatterns(patterns: PatternEntry[]): PatternEntry[] {
  return patterns.filter((entry, index) => !patterns
    .slice(0, index)
    .some(candidate => entry.pattern.includes(candidate.pattern)))
}

export function generateBotMatcherModule(definitions: readonly BotCategoryDefinition[]): string {
  const patterns = removeShadowedPatterns(collectPatterns(definitions))
  const botTargets = patterns.map(({ definitionIndex, botIndex }) => {
    if (definitionIndex > 255 || botIndex > 255)
      throw new Error('Bot matcher target exceeds its 8-bit index limit.')
    return (definitionIndex << 8) | botIndex
  })
  const alternatives = patterns.map(({ pattern }) => `(${escapeRegExpPattern(pattern)})`).join('|')

  return `// Generated by build.config.ts. Do not edit.

const defaultBotPattern = /(?=${alternatives})/g
const botTargets: number[] = [${botTargets.join(', ')}]

export function matchDefaultBotTarget(value: string): number | undefined {
  let bestPriority = -1
  defaultBotPattern.lastIndex = 0
  let match = defaultBotPattern.exec(value)
  while (match) {
    let priority = 0
    while (typeof match[priority + 1] === 'undefined')
      priority++
    if (bestPriority === -1 || priority < bestPriority)
      bestPriority = priority
    if (bestPriority === 0)
      break
    defaultBotPattern.lastIndex = match.index + 1
    match = defaultBotPattern.exec(value)
  }
  return bestPriority === -1 ? undefined : botTargets[bestPriority]
}
`
}
