interface BotPatternDefinition {
  name: string
  pattern: string
  secondaryPatterns?: string[]
}

interface BotCategoryDefinition {
  bots: BotPatternDefinition[]
  trusted: boolean
  type: string
}

interface PatternEntry {
  botIndex: number
  definitionIndex: number
  pattern: string
  priority: number
}

interface MatcherNode {
  failure: number
  output: number
  transitions: Map<string, number>
}

function collectPatterns(definitions: readonly BotCategoryDefinition[]): PatternEntry[] {
  const patterns = new Map<string, PatternEntry>()
  for (const [definitionIndex, definition] of definitions.entries()) {
    for (const [botIndex, bot] of definition.bots.entries()) {
      for (const sourcePattern of [bot.pattern, ...(bot.secondaryPatterns || [])]) {
        const pattern = sourcePattern.toLowerCase()
        const current = patterns.get(pattern)
        patterns.set(pattern, {
          botIndex,
          definitionIndex,
          pattern,
          priority: current?.priority ?? patterns.size,
        })
      }
    }
  }
  return [...patterns.values()]
}

function mergeOutput(node: MatcherNode, failureNode: MatcherNode) {
  if (failureNode.output !== -1 && (node.output === -1 || failureNode.output < node.output))
    node.output = failureNode.output
}

function compileMatcher(patterns: PatternEntry[]): MatcherNode[] {
  const nodes: MatcherNode[] = [{ failure: 0, output: -1, transitions: new Map() }]
  for (const entry of patterns) {
    let state = 0
    for (let index = 0; index < entry.pattern.length; index++) {
      const character = entry.pattern[index]!
      let nextState = nodes[state]!.transitions.get(character)
      if (typeof nextState === 'undefined') {
        nextState = nodes.length
        nodes[state]!.transitions.set(character, nextState)
        nodes.push({ failure: 0, output: -1, transitions: new Map() })
      }
      state = nextState
    }
    nodes[state]!.output = entry.priority
  }

  const queue: number[] = []
  for (const child of nodes[0]!.transitions.values()) {
    mergeOutput(nodes[child]!, nodes[0]!)
    queue.push(child)
  }
  for (let cursor = 0; cursor < queue.length; cursor++) {
    const state = queue[cursor]!
    for (const [character, child] of nodes[state]!.transitions) {
      let fallback = nodes[state]!.failure
      while (fallback !== 0 && !nodes[fallback]!.transitions.has(character))
        fallback = nodes[fallback]!.failure
      const childNode = nodes[child]!
      childNode.failure = nodes[fallback]!.transitions.get(character) ?? 0
      mergeOutput(childNode, nodes[childNode.failure]!)
      queue.push(child)
    }
  }
  return nodes
}

function serializeUint16(values: number[]): string {
  if (values.some(value => value < 0 || value > 65_503))
    throw new Error('Bot matcher table exceeds its 16-bit value limit.')
  return JSON.stringify(String.fromCharCode(...values.map(value => value + 32)))
}

export function generateBotMatcherModule(definitions: readonly BotCategoryDefinition[]): string {
  const patterns = collectPatterns(definitions)
  const nodes = compileMatcher(patterns)
  const transitionOffsets = [0]
  const transitionCharacters: string[] = []
  const transitionTargets: number[] = []
  for (const node of nodes) {
    for (const [character, target] of node.transitions) {
      transitionCharacters.push(character)
      transitionTargets.push(target)
    }
    transitionOffsets.push(transitionTargets.length)
  }
  const failures = nodes.map(node => node.failure)
  const outputs = nodes.map(node => node.output + 1)
  const botTargets = patterns.map(({ definitionIndex, botIndex }) => {
    if (definitionIndex > 255 || botIndex > 255)
      throw new Error('Bot matcher target exceeds its 8-bit index limit.')
    return (definitionIndex << 8) | botIndex
  })

  return `/* eslint-disable style/comma-spacing, style/key-spacing, style/object-curly-spacing, style/quote-props, style/quotes */
// Generated by build.config.ts. Do not edit.

const transitionOffsets = ${serializeUint16(transitionOffsets)}
const transitionCharacters = ${JSON.stringify(transitionCharacters.join(''))}
const transitionTargets = ${serializeUint16(transitionTargets)}
const failures = ${serializeUint16(failures)}
const outputs = ${serializeUint16(outputs)}
const botTargets = ${serializeUint16(botTargets)}

function findTransition(state: number, character: number): number | undefined {
  for (let index = transitionOffsets.charCodeAt(state) - 32; index < transitionOffsets.charCodeAt(state + 1) - 32; index++) {
    if (transitionCharacters.charCodeAt(index) === character)
      return transitionTargets.charCodeAt(index) - 32
  }
}

export function matchDefaultBotTarget(value: string): number | undefined {
  let state = 0
  let bestPriority = outputs.charCodeAt(0) - 33
  for (let index = 0; index < value.length; index++) {
    const character = value.charCodeAt(index)
    let nextState = findTransition(state, character)
    while (typeof nextState === 'undefined' && state !== 0) {
      state = failures.charCodeAt(state) - 32
      nextState = findTransition(state, character)
    }
    state = nextState ?? 0
    const priority = outputs.charCodeAt(state) - 33
    if (priority !== -1 && (bestPriority === -1 || priority < bestPriority)) {
      bestPriority = priority
      if (bestPriority === 0)
        break
    }
  }
  return bestPriority === -1 ? undefined : botTargets.charCodeAt(bestPriority) - 32
}
`
}
