/* eslint-disable style/comma-spacing, style/key-spacing, style/object-curly-spacing, style/quote-props, style/quotes */
// Generated by build.config.ts. Do not edit.

const transitionOffsets = " 356789<=>?@ABCDEFGHIJKKOPQRSTTWXYZ[[\\]^_`abccdefhijklmmnopprstuvwxz{||}~ ¡¢¢£¤¥¦§¨©ª««¬­®¯°±²´µ¶·¸¹º»¼½¾¾¿ÀÁÁÂÃÄÅÆÇÈÉÊËËÑÒÓÔÕÖ×ØÙÚÛÛÝÞßàáãäååæççèéêëììîïðñòóôõö÷øùúûüýþÿÿĀāĂăąĆććĈĉĊĊČčĎďĐĒēĔĔĕĖėĘęĚěěĜĞğĠġĢģĥĦħĨĩĩĪīĬĭĮįİıĲĲĳĴĵĶķĸĹĹĺĻļĽľĿŀŀŅņŇňŉŉŊŋŌōōŎŏŐőŒœŔŕŖŖŗŘřŚśŜŝŞŞşŠšŢţŤťŦŦŧŨũŪūŬŭŮŮůŰűŲŲųŴŵŶŶŸŹźŻżŽžſſƀƁƂƂƃƄƅƆƇƈƉƊƋƌƍƎƎƏƐƑƒƓƔƕƖƘƙƚƚƛƜƜƝƝƞƟƠơơƢƣƤƥƦƦƧƩƪƪƫƬƭƮƯưƱƱƲƳƴƵƶƷƸƸƹƺƻƼƽƾƿǀǀǁǂǃǄǅǅǈǉǊǋǌǍǎǏǏǐǑǒǓǔǕǖǖǗǘǙǚǛǜǝǞǟǠǡǢǣǣǤǥǥǦǧǧǨǩǪǫǫǬǭǮǯǯǱǲǳǳǴǵǶǷǸǹǺǻǼǽǾǾǿȀȁȁȂȃȄȅȅȆȇȈȉȉ"
const transitionCharacters = "gbmydsatflprcohwzniopogleb.-ot-com/bot.htmliayongbotsjanbotandexbotidus.pidercomuickduckbgoto.comlecpurpphnpleb.ot-com/go/applebotwitterbotacebooke.xternalhitcominkedinbotiehluynterestbotsfcordbaotpp12botjsestic12.co.uk/botrefsb.otcommlrushb.otcom/botreaaming ffrogrog.co.ukogerbotthropiclocruaudetbotpenai.comextendedextendedtespiderfbotnewshmere.combotmoncrawl.orgrplexityb.otaitiderawlerpeyrantomjseadlessaywrighteniumegpbdriverppeteerthon-requestsetrlgrabscanmiapnsecure.orgktoscan.org"
const transitionTargets = "!7>D[lqªµĚĪĵƦƽǢǬǰ\"İ#$%&'*Ŀ()ş+,-./01234568Mőƍ9:;<=?ÍÓ@ABCEFGHIJKLNOPQWRSTUVXYZ\\Á]^_`abcfdeghijkmòăƏnopræĢstuvywxňz{|}~¦ ¡¢£¤¥§¨©«¬­®¯°±²³´¶žƞƮǆǎ·¸¹º»¼½¾¿ÀÂŚÃÄÅÆÇÊÈÉËÌÎÏÐÑÒÔǧÕÖ×ØÙÚÛÜÝÞßàáâãäåçèéêëîìíïðñóƷôõö÷øûùúüýþÿĀāĂĄąƚĆćĈĉĊċĐČčĎďđĒēĔĕĖėĘęěĜĝĞğĠġģĤĥĦħĨĩīŤŭƔǟĬĭĮįıĲĳĴĶķĸĹĺĻļĽľŀŁłŃńŅņŇŉŊŋŌōŎŏŐŒœŔŕŖŗŘřśŜŝŞŠšŢţťűŦŧŨũŪūŬŮůŰŲųŴŵŶŷŸŹźŻżŽſƀƁƂƃƄƅƆƇƊƈƉƋƌƎƐƑƒƓƕƖƗƘƙƛƜȅƝƟƠơƢƣƤƥƧƨƩƪƫƬƭƯưƱƲƳƴƵƶƸƹƺƻƼƾǜȀƿǀǁǂǃǄǅǇǈǉǊǋǌǍǏǐǑǒǓǔǕǖǗǘǙǚǛǝǞǠǡǣǤǥǦǨǩǪǫǭǼǮǯǱǲǳǴǵǶǷǸǹǺǻǽǾǿȁȂȃȄȆȇȈȉ"
const failures = "  ĵĵ!ª 7ƍƎ ĪŤű 7ƍƎ Ʀ>ª ǰǱ!7ƍƎ lǬ7ƍƎ qĢ[  7ƍƎqǰ[\\lƏƐƑƒƓ ĪŤű  Ī [\\]^7ƍƎ!\" ĪŤű ª Ěµ µµƮ 7ƍƎ ĪŤű !\" qrstuvwx ƽǰ Ě7ƍƎ qĪ 7ƍĵ    ĚǬqªƦǰ ĪŤű ǰǱ  [ÁǱ7ƍƎ ǰǱ Ě l7ƍƎǰlăŤĚ[7ƍƎqrs   7ƍƎq  lǰĪ   ĪŤ    7ƍƎƦĚ l7ƍƎ ĪŤű >Ě lƦ7ƍƎ ĪŤű 7ƍƎĪƔ q>ǰǱ! ĚěĜĚěĜ ĪŤ    ĵ! Ě7ƍƎǬƦĚěĶ¶Ī ªq [ µ7ƍƎ µžǬqǰ ĪŤű    Ǭ[ [    Ǭ[ [D lƏƐƑƒƓ7ƍƎ Ǭ ƽlĵƦƧĚ  ĪŤűĪ7ƍƎ>>ĵǬĪƔƕƖƗ ĵĚ! ĚµƮ  ǰD7ƍƎ qǰĵµ¶[ ĚĚqƽª ĚƕržſƦqĢģĵ>Íl  q[ª llªqDƽĚǰ!Ʀª ǬǼ >  7[Ěǰ  Ě µµž  ĚDƦĵǬ Ě    ll!  Ěª !Ěq7llăqĢ >Ór ǬlòĪǟǠ  ĵĚ!ǰ ĵµlăqĢǎ ĵĚ!"
const outputs = "         !       O    \"      #     $        %         &   '          (     )    *       +               +      .  -                  /   0       2  1        4  3        5  6     7                  8       9   :        ;       <            =         >       ?       @     A    B         C        D        E        F    G    H    I   J   K            L           M  N O    P     Q   R       S       T        U     V        W       X    Z        Y  [  \\    ]    ^   _           `   a    bc   d"
const botTargets = "  !!\"##$$%&&ĠĠġġĢĢģģĤĤȠȠȡȡȢȢȣȣȤ̡̢̢̧̨̨̠̣̤̥̦̩̩̪̪РСТУԠԤԢԣԣԤؠؠءآܠܡܢܢܣܤࠠࠠ"

function findTransition(state: number, character: number): number | undefined {
  for (let index = transitionOffsets.charCodeAt(state) - 32; index < transitionOffsets.charCodeAt(state + 1) - 32; index++) {
    if (transitionCharacters.charCodeAt(index) === character)
      return transitionTargets.charCodeAt(index) - 32
  }
}

export function matchDefaultBotTarget(value: string): number | undefined {
  let state = 0
  let bestPriority = outputs.charCodeAt(0) - 33
  for (let index = 0; index < value.length; index++) {
    const character = value.charCodeAt(index)
    let nextState = findTransition(state, character)
    while (typeof nextState === 'undefined' && state !== 0) {
      state = failures.charCodeAt(state) - 32
      nextState = findTransition(state, character)
    }
    state = nextState ?? 0
    const priority = outputs.charCodeAt(state) - 33
    if (priority !== -1 && (bestPriority === -1 || priority < bestPriority)) {
      bestPriority = priority
      if (bestPriority === 0)
        break
    }
  }
  return bestPriority === -1 ? undefined : botTargets.charCodeAt(bestPriority) - 32
}
