import { addTemplate, useNuxt } from '@nuxt/kit'
import { resolve } from 'pathe'

export function extendTypes(module: string, template: () => string | Promise<string>) {
  const nuxt = useNuxt()
  // paths.d.ts
  addTemplate({
    filename: `module/${module}.d.ts`,
    getContents: async () => {
      const s = await template()
      return `// Generated by ${module}
${s}
export {}
`
    },
  })

  nuxt.hooks.hook('prepare:types', ({ references }) => {
    references.push({ path: resolve(nuxt.options.buildDir, `module/${module}.d.ts`) })
  })
}
