import type { Nuxt } from '@nuxt/schema'
import type { ModuleOptions } from './module'
import { addTypeTemplate, isNuxtMajorVersion } from '@nuxt/kit'

interface TemplateContext {
  nuxt: Nuxt
  config: ModuleOptions
}

export function registerTypeTemplates({ nuxt }: TemplateContext) {
  // Nuxt 4 ships Nitro v3, which exposes `nitropack/types` as a public subpath.
  // @nuxt/kit's extendRouteRules unions NitroRouteConfig across both 'nitropack'
  // and 'nitropack/types', so augmenting only one leaves the other's re-exported
  // interface without our `robots` key.
  const nitroModules = isNuxtMajorVersion(4, nuxt)
    ? ['nitropack', 'nitropack/types']
    : ['nitropack']

  // Nuxt-only type augmentations (PageMeta)
  addTypeTemplate({
    filename: 'types/nuxt-robots-nuxt.d.ts',
    getContents: () => `// Generated by nuxt-robots
import type { RobotsValue } from '@nuxtjs/robots'

declare module '#app' {
  interface PageMeta {
    robots?: RobotsValue
  }
}

export {}
`,
  }, {
    nuxt: true,
  })

  const nitroAugmentation = (mod: string) => `declare module '${mod}' {
  interface NitroApp {
    _robots: {
      ctx: HookRobotsConfigContext
      nuxtContentUrls?: Set<string>
    },
    _robotsRuleMatcher: (url: string) => any
    _robotsPatternMap?: Map<string, PatternMapValue>
  }
  interface NitroRouteRules {
    robots?: RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRouteConfig {
    robots?: RobotsValue | {
      indexable: boolean
      rule: string
    }
  }
  interface NitroRuntimeHooks {
    'robots:config': (ctx: HookRobotsConfigContext) => void | Promise<void>
    'robots:robots-txt': (ctx: HookRobotsTxtContext) => void | Promise<void>
  }
}`

  // Nitro type augmentations (NitroApp, NitroRouteRules, NitroRouteConfig, NitroRuntimeHooks, H3EventContext)
  addTypeTemplate({
    filename: 'types/nuxt-robots-nitro.d.ts',
    getContents: () => `// Generated by nuxt-robots
import type { HookRobotsConfigContext, HookRobotsTxtContext, RobotsValue, RobotsContext, PatternMapValue } from '@nuxtjs/robots'

${nitroModules.map(nitroAugmentation).join('\n\n')}

declare module 'h3' {
  interface H3EventContext {
    robots: RobotsContext
    robotsProduction?: RobotsContext
  }
}

export {}
`,
  }, {
    nitro: true,
    nuxt: true,
  })
}
