name: Package Size Analysis

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    uses: harlan-zw/nuxt-seo/.github/workflows/reusable-package-size.yml@226c091a0744b7286ef721ac035eed53856bfaa5
    with:
      migration: true
